<a id="inicio"></a>
# Obtener datos de Idealista


1. [Importar librerías](#import)
2. [Definición de Constantes](#constants)
3. [Obtener datos de Idealista](#get_data)

 <a id="import"></a>
## Importar librerías

In [1]:
import time
import os
import sys
sys.path.append(r"../")

import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import linear_model

import utils.idealistatools as idealistatools

 <a id="constants"></a>
## Definición de Constantes

In [4]:
DATA_PATH = "data"

 <a id="get_data"></a>
## Obtener datos de Idealista

In [3]:
idealista = idealistatools.Idealista(debug = True)
center = '40.44,-3.71'
distance = '20000'

In [5]:
my_api_key = ""
my_api_secret = ""
idealista.generate_token(api_key=my_api_key, api_secret=my_api_secret)

'\nmy_api_key = ""\nmy_api_secret = ""\nidealista.generate_token(api_key=my_api_key, api_secret=my_api_secret)\n'

In [4]:
totalPages = 1382
pagIni = 1
for pagina in range(pagIni, totalPages):
    if (pagina - 1) % 20 == 0:
        print(str(pagina))
    result = idealista.search(numPage=str(pagina),center=center,distance=distance)
    summary = idealista.summary_result(result)
    idealista.elementlist_tojson(result, 'idealista_' + str(pagina) + ".json")
    time.sleep(10)

http://api.idealista.com/3.5/es/search?country=es&center=40.44,-3.71&numPage=586&maxItems=50&distance=20000&propertyType=homes&operation=sale
Error: Expecting value: line 1 column 1 (char 0)
r.text:

TypeError: 'NoneType' object is not subscriptable

In [11]:
idealista_df = idealista.read_json('idealista_1.json')

In [86]:
idealista_df.head()

,propertyCode,thumbnail,externalReference,numPhotos,floor,price,propertyType,operation,size,exterior,...,hasLift,priceByArea,detailedType,suggestedTexts,hasPlan,has3DTour,has360,hasStaging,topNewDevelopment,parkingSpace
0,93868909,https://img3.idealista.com/blur/WEB_LISTING/0/...,lm161734,32,5,690000,flat,sale,130,False,...,1.0,5308,{'typology': 'flat'},"{'subtitle': 'Ibiza, Madrid', 'title': 'Piso'}",True,True,False,False,False,NaN
1,93294614,https://img3.idealista.com/blur/WEB_LISTING/0/...,AM159809,40,bj,895000,flat,sale,277,True,...,1.0,3231,{'typology': 'flat'},"{'subtitle': 'Arroyo de la Vega, La Moraleja',...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
2,93836396,https://img3.idealista.com/blur/WEB_LISTING/0/...,V6600I,59,NaN,1890000,chalet,sale,401,False,...,NaN,4713,"{'typology': 'chalet', 'subTypology': 'semidet...","{'subtitle': 'Encinar de los Reyes, La Moralej...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
3,93242574,https://img3.idealista.com/blur/WEB_LISTING/0/...,MV3938I,51,2,1220000,flat,sale,190,True,...,1.0,6421,{'typology': 'flat'},"{'subtitle': 'Almagro, Madrid', 'title': 'Piso'}",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
4,93067738,https://img3.idealista.com/blur/WEB_LISTING/0/...,V5343I,49,2,998000,flat,sale,191,True,...,1.0,5225,{'typology': 'flat'},"{'subtitle': 'El Soto de la Moraleja, La Moral...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."

In [87]:
idealista_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   propertyCode       20 non-null     int64
 1   thumbnail          20 non-null     object
 2   externalReference  20 non-null     object
 3   numPhotos          20 non-null     int64
 4   floor              12 non-null     object
 5   price              20 non-null     int64
 6   propertyType       20 non-null     object
 7   operation          20 non-null     object
 8   size               20 non-null     int64
 9   exterior           20 non-null     bool
 10  rooms              20 non-null     int64
 11  bathrooms          20 non-null     int64
 12  address            20 non-null     object
 13  province           20 non-null     object
 14  municipality       20 non-null     object
 15  district           20 non-null     object
 16  country            20 non-null     object
 17  neighborhood       4 non-null      object
 18  latitude           20 non-null     float64
 19  longitude          20 non-null     float64
 20  showAddress        20 non-null     bool
 21  url                20 non-null     object
 22  distance           20 non-null     int64
 23  hasVideo           20 non-null     bool
 24  status             20 non-null     object
 25  newDevelopment     20 non-null     bool
 26  hasLift            12 non-null     float64
 27  priceByArea        20 non-null     int64
 28  detailedType       20 non-null     object
 29  suggestedTexts     20 non-null     object
 30  hasPlan            20 non-null     bool
 31  has3DTour          20 non-null     bool
 32  has360             20 non-null     bool
 33  hasStaging         20 non-null     bool
 34  topNewDevelopment  20 non-null     bool
 35  parkingSpace       17 non-null     object
dtypes: bool(9), float64(3), int64(8), object(16)
memory usage: 4.5+ KB

In [88]:
idealista_df.loc[:5,'address':'neighborhood']

,address,province,municipality,district,country,neighborhood
0,barrio Ibiza,Madrid,Madrid,Retiro,es,Ibiza
1,Avenida de Rafael Nadal,Madrid,La Moraleja,Arroyo de la Vega,es,NaN
2,Encinar de los Reyes,Madrid,La Moraleja,Encinar de los Reyes,es,NaN
3,barrio Almagro,Madrid,Madrid,Chamberí,es,Almagro
4,Calle de la Hiedra,Madrid,La Moraleja,El Soto de la Moraleja,es,NaN
5,Vereda de Palacio,Madrid,La Moraleja,Encinar de los Reyes,es,NaN

In [14]:
idealista_df.loc[:5,'distance':'priceByArea']

   distance  hasVideo status  newDevelopment  hasLift  priceByArea
0      3975      True   good           False      1.0         5308
1     13693      True   good           False      1.0         3231
2      9690      True   good           False      NaN         4713
3      1481      True  renew           False      1.0         6421
4     10943      True   good           False      1.0         5225
5      9397      True   good           False      1.0         6100

In [89]:
idealista_df.loc[:5,'detailedType':]

,detailedType,suggestedTexts,hasPlan,has3DTour,has360,hasStaging,topNewDevelopment,parkingSpace
0,{'typology': 'flat'},"{'subtitle': 'Ibiza, Madrid', 'title': 'Piso'}",True,True,False,False,False,NaN
1,{'typology': 'flat'},"{'subtitle': 'Arroyo de la Vega, La Moraleja',...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
2,"{'typology': 'chalet', 'subTypology': 'semidet...","{'subtitle': 'Encinar de los Reyes, La Moralej...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
3,{'typology': 'flat'},"{'subtitle': 'Almagro, Madrid', 'title': 'Piso'}",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
4,{'typology': 'flat'},"{'subtitle': 'El Soto de la Moraleja, La Moral...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."
5,{'typology': 'flat'},"{'subtitle': 'Encinar de los Reyes, La Moralej...",True,True,False,True,False,"{'hasParkingSpace': True, 'isParkingSpaceInclu..."

In [91]:
idealista_df.at[5,'parkingSpace']

{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': True}

In [12]:
idealista_df.at[2,'detailedType']

{'typology': 'chalet', 'subTypology': 'semidetachedHouse'}

In [3]:
idealista_df = idealista.read_jsons()
idealista.clean_dataframe(idealista_df)
idealista_df

,propertyCode,thumbnail,externalReference,numPhotos,floor,price,propertyType,operation,size,exterior,...,suggestedTexts,hasPlan,has3DTour,has360,hasStaging,topNewDevelopment,newDevelopmentFinished,subTypology,hasParkingSpace,isParkingSpaceIncludedInPrice
0,93868909,https://img3.idealista.com/blur/WEB_LISTING/0/...,lm161734,32,5,690000,flat,sale,130.0,False,...,"{'subtitle': 'Ibiza, Madrid', 'title': 'Piso'}",True,True,False,False,False,NaN,,NaN,NaN
1,93294614,https://img3.idealista.com/blur/WEB_LISTING/0/...,AM159809,40,bj,895000,flat,sale,277.0,True,...,"{'subtitle': 'Arroyo de la Vega, La Moraleja',...",True,True,False,True,False,NaN,,True,True
2,93836396,https://img3.idealista.com/blur/WEB_LISTING/0/...,V6600I,59,NaN,1890000,chalet,sale,401.0,False,...,"{'subtitle': 'Encinar de los Reyes, La Moralej...",True,True,False,True,False,NaN,semidetachedHouse,True,True
3,93242574,https://img3.idealista.com/blur/WEB_LISTING/0/...,MV3938I,51,2,1220000,flat,sale,190.0,True,...,"{'subtitle': 'Almagro, Madrid', 'title': 'Piso'}",True,True,False,True,False,NaN,,True,True
4,93067738,https://img3.idealista.com/blur/WEB_LISTING/0/...,V5343I,49,2,998000,flat,sale,191.0,True,...,"{'subtitle': 'El Soto de la Moraleja, La Moral...",True,True,False,True,False,NaN,,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,90254228,https://img3.idealista.com/blur/WEB_LISTING/0/...,VM2007009,16,bj,290000,flat,sale,48.0,True,...,"{'subtitle': 'Colina, Madrid', 'title': 'Piso'}",True,False,False,False,False,NaN,,True,True
11696,87878805,https://img3.idealista.com/blur/WEB_LISTING/0/...,VM1911049,19,1,850000,flat,sale,160.0,True,...,"{'subtitle': 'Huertas-Cortes, Madrid', 'title'...",True,False,False,False,False,NaN,,NaN,NaN
11697,87375364,https://img3.idealista.com/blur/WEB_LISTING/0/...,VM1910036,19,2,1250000,flat,sale,220.0,True,...,"{'subtitle': 'Malasaña-Universidad, Madrid', '...",True,False,False,False,False,NaN,,NaN,NaN
11698,85504146,https://img3.idealista.com/blur/WEB_LISTING/0/...,VM1811046,32,4,1950000,flat,sale,289.0,True,...,"{'subtitle': 'Goya, Madrid', 'title': 'Piso'}",False,False,False,False,False,NaN,,NaN,NaN
11699,91407242,https://img3.idealista.com/blur/WEB_LISTING/0/...,Bajo B,14,bj,696000,duplex,sale,126.0,True,...,"{'subtitle': 'Peñagrande, Madrid', 'title': 'D...",True,False,False,False,False,0.0,duplex,True,True

In [4]:
idealista_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11700 entries, 0 to 11699
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   propertyCode                   11700 non-null  int64
 1   thumbnail                      11678 non-null  object
 2   externalReference              10357 non-null  object
 3   numPhotos                      11700 non-null  int64
 4   floor                          9510 non-null   object
 5   price                          11700 non-null  int64
 6   propertyType                   11700 non-null  object
 7   operation                      11700 non-null  object
 8   size                           11700 non-null  float64
 9   exterior                       11700 non-null  bool
 10  rooms                          11700 non-null  int64
 11  bathrooms                      11700 non-null  int64
 12  address                        11700 non-null  object
 13  province                       11700 non-null  object
 14  municipality                   11700 non-null  object
 15  district                       11613 non-null  object
 16  country                        11700 non-null  object
 17  neighborhood                   9771 non-null   object
 18  latitude                       11700 non-null  float64
 19  longitude                      11700 non-null  float64
 20  showAddress                    11700 non-null  bool
 21  url                            11700 non-null  object
 22  distance                       11700 non-null  int64
 23  hasVideo                       11700 non-null  bool
 24  status                         11698 non-null  object
 25  newDevelopment                 11700 non-null  bool
 26  hasLift                        9802 non-null   float64
 27  priceByArea                    11700 non-null  int64
 28  suggestedTexts                 11700 non-null  object
 29  hasPlan                        11700 non-null  bool
 30  has3DTour                      11700 non-null  bool
 31  has360                         11700 non-null  bool
 32  hasStaging                     11700 non-null  bool
 33  topNewDevelopment              11700 non-null  bool
 34  newDevelopmentFinished         746 non-null    float64
 35  subTypology                    11700 non-null  object
 36  hasParkingSpace                4794 non-null   object
 37  isParkingSpaceIncludedInPrice  4794 non-null   object
dtypes: bool(9), float64(5), int64(7), object(17)
memory usage: 2.7+ MB

In [5]:
idealista_df.to_csv(os.path.join(DATA_PATH, 'idealista.csv'), index=False)

[Ir a inicio](#inicio)